openapi: 3.0.2
info:
  title: Medods test auth API
  description: Test JWT API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local development server

paths:
  /api/v1/auth/login:
    post:
      parameters:
        - name: guid
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "refresh_token=eyJhbGci...; HttpOnly; Secure; SameSite=Strict; Path=/"
          content:
            application/json:
                schema:
                  type: object
                  properties:
                    access_token:
                      type: string
                      example: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/auth/refresh:
    post:
      parameters:
        - name: refresh_token
          in: cookie
          schema:
            type: string
            example: "refresh_token=eyJhbGci...; HttpOnly; Secure; SameSite=Strict; Path=/"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                  example: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA


      responses:
        '200':
          description: Success
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "refresh_token=eyJhbGci...; HttpOnly; Secure; SameSite=Strict; Path=/"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

